<!doctype html>
<html>
<head>
	<link rel="stylesheet" media="screen" href="/web/style.css"/>
	<link rel="icon" type="image/x-icon" href="/web/favicon.ico">
</head>
<body>

<style>
#body {
	padding: 50px;
}
textarea {
	margin: auto;
	width:100%;
	height: 82vh;
}
</style>


<form method="POST">
<div id="body">
	<textarea name="raw">${raw}</textarea>
	<input type="submit" value="save" />
</div>
</form>

</body>
